insert into Airports (name, city, runwaycapacity, storecapacity) values ('Chalkyitsik Airport', 'Zhihe', 81, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Antwerp International Airport (Deurne)', 'Khun Han', 44, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Atmautluak Airport', 'San Juan', 58, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dubois Municipal Airport', 'Rio do Sul', 42, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Namsang Airport', 'Zhuanqiang', 21, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Muskoka Airport', 'Tugu', 84, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Perry-Foley Airport', 'Velké Bílovice', 27, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Malakal Airport', 'Borzoy', 31, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('St. Peter-Ording Airport', 'Iaçu', 22, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('St Clair County Airport', 'Seixal', 85, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tauta Airport', 'Catujal', 22, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kenmore Air Harbor Seaplane Base', 'Dobrica', 19, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zahn''s Airport', 'Muyaka', 45, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Watertown International Airport', 'Brive-la-Gaillarde', 21, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jasper County Airport', 'Lazdijai', 46, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jersey Airport', 'Saint-Denis', 23, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pinar Del Rio Airport', 'Longquan', 47, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Júlio de Castilho Airport', 'Perdões', 38, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Chimore Airport', 'Barnaul', 43, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jaqué Airport', 'Dolní Libina', 85, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Great Bear Lake Airport', 'Al ‘Ashshah', 47, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Soledade Airport', '‘Afak', 39, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sicogon Airstrip', 'Saint-Denis', 13, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kurumoch International Airport', 'Hualongyan', 33, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Injune Airport', 'Huangzhan', 18, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ciudad Obregón International Airport', 'Gaïtánion', 19, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kerau Airport', 'Tierralta', 54, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Puerto Cabezas Airport', 'Taraš', 45, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dahl Creek Airport', 'Changning', 56, 48);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Courchevel Airport', 'Erie', 23, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Irkutsk Airport', 'Sonder', 55, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sacramento Mather Airport', 'Pokrovskoye', 4, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Devonport Airport', 'Pyatnitskoye', 78, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cayenne-Rochambeau Airport', 'San Francisco', 43, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Columbia Regional Airport', 'Lau', 91, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Butterworth Airport', 'El’brus', 90, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tumolbil Airport', 'Otradnyy', 6, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sandakan Airport', 'Maragogi', 28, 13);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zhob Airport', 'Parachinar', 14, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dax Seyresse Airport', 'Korczyna', 45, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Geneina Airport', 'Néa Róda', 64, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Philadelphia Seaplane Base', 'Cikeper', 49, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Naypyidaw Airport', 'Ciladaeun', 59, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jamestown Regional Airport', 'Calumpang', 49, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Notodden Airport', 'Seredka', 27, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Comandante Gustavo Kraemer Airport', 'Karibib', 49, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Berlin Regional Airport', 'Ręczno', 52, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Craig Seaplane Base', 'Kasukabe', 15, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tikehau Airport', 'Taupo', 62, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tingwon Airport', 'Corinto', 6, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nunapitchuk Airport', 'Xiting', 35, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Djerba Zarzis International Airport', 'Jiworejo', 58, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Okadama Airport', 'Kousséri', 49, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Perry Stokes Airport', 'Malczyce', 46, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bakkafjörður Airport', 'Kedungcangkring', 49, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kerama Airport', 'Nyazura', 18, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bouarfa Airport', 'Santa Lucia', 52, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rawlins Municipal Airport/Harvey Field', 'Huacaschuque', 41, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Udorn Air Base', 'Båstad', 26, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bangor International Airport', 'Vinsady', 32, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Detroit Lakes Airport - Wething Field', 'Junshan', 89, 48);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bagdad Airport', 'Jetak', 59, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bishe Kola Air Base', 'Sekartaji', 58, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Grootfontein Airport', 'Rimpakgede', 71, 48);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bachigualato Federal International Airport', 'Tallkalakh', 42, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yellowknife Airport', 'Lāliān', 99, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nouadhibou International Airport', 'Querocotillo', 67, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ficksburg Sentraoes Airport', 'Daixi', 40, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Negarbo(Negabo) Airport', 'Zhourui', 95, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lumbala Airport', 'Leku', 7, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Torrejón Airport', 'Vredenburg', 45, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mersing Airport', 'Apengjiang', 7, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cape Rodney Airport', 'Fatubia', 24, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yeniseysk Airport', 'Postupice', 99, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Santa Paula Airport', 'Budënnovsk', 64, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ellington Airport', 'Santa Elena', 26, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Awassa Airport', 'Carmen', 76, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Grafton Airport', 'Novosemeykino', 22, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Palm Island Airport', 'Vyšší Brod', 8, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mamai Airport', 'Wucun', 43, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Canefield Airport', 'Daqiao', 32, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Luozi Airport', 'Al Abyār', 88, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('McGhee Tyson Airport', 'Quxi', 30, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nicaro Airport', 'Waterloo', 85, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cape Barren Island Airport', 'Pivovarikha', 71, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Francisco Primo de Verdad y Ramos Airport', 'Santiago Puringla', 37, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Orange Airport', 'Tiglauigan', 51, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Baindoung Airport', 'Prínos', 21, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gold Beach Municipal Airport', 'Taranovskoye', 26, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lawrence J Timmerman Airport', 'Yartsevo', 70, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Daniel K Inouye International Airport', 'Lindong', 93, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mondell Field', 'Žiežmariai', 14, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ekwok Airport', 'San Francisco', 21, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Juwata Airport', 'Persen', 49, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Antonio Nery Juarbe Pol Airport', 'Tajao', 13, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gitega Airport', 'Laoshawan', 18, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ada Regional Airport', 'Hato Mayor del Rey', 90, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Carnot Airport', 'Kedungdoro', 87, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tshipise Airport', 'Tatuí', 29, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Guarani International Airport', 'Lakateng', 48, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('John F Kennedy Memorial Airport', 'Currais Novos', 30, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Orsk Airport', 'Simbal', 10, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bacolod-Silay Airport', 'Quartier Morin', 42, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Broken Bow Municipal Airport', 'Manoel Urbano', 85, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Treinta y Tres Airport', 'Sanqiao', 40, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Guangzhou Baiyun International Airport', 'Calauan', 71, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Port Graham Airport', 'Bulungu', 45, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Xinguara Municipal Airport', 'Sa''dah', 83, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Niagara District Airport', 'Perez', 5, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('New Castle Airport', 'Fuerte', 4, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Merrill Municipal Airport', 'Gračac', 7, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dallas Love Field', 'Kudinovo', 71, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tajima Airport', 'Huangben', 62, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dauphin Barker Airport', 'Kivsharivka', 29, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yakutat Airport', 'Río de Oro', 16, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sary-Arka Airport', 'Bum Bum', 69, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Miandrivazo Airport', 'Vidče', 69, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Suai Airport', 'San Francisco', 46, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ibiza Airport', 'Višnjićevo', 11, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Whangarei Airport', 'Jamban', 22, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Manitoulin East Municipal Airport', 'Siwalan', 79, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Stewart Airport', 'Wudabao', 42, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bacău Airport', 'Esil', 72, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tabas Airport', 'Wenping', 60, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rae Lakes Airport', 'Santo Tomas', 4, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Woomera Airfield', 'Bīr Nabālā', 66, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pantelleria Airport', 'Brodarica', 100, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sambava Airport', 'Martingança-Gare', 83, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Vir Savarkar International Airport', 'Unión', 57, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Foothills Regional Airport', 'Żabieniec', 65, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Laconia Municipal Airport', 'Stari Bar', 81, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ogoki Post Airport', 'Dampit', 83, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Preah Vinhear Airport', 'São Pedro Gafanhoeira', 36, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Griffiss International Airport', 'Qishn', 6, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fort Lee Army Airfield', 'Châteauroux', 3, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Oswaldo Guevara Mujica Airport', 'Bački Petrovac', 4, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Oscoda Wurtsmith Airport', 'Basyūn', 6, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pimaga Airport', 'Alor Setar', 9, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hatbox Field', 'Canhestros', 36, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mariquita Airport', 'Nivnice', 70, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Armidale Airport', 'Lokossa', 3, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ust-Maya Airport', 'Partikan', 58, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kebar Airport', 'Huilelot', 22, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Purwokerto Airport', 'Shijiazhai', 1, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Orlando Sanford International Airport', 'Zhongchao', 32, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('La Nubia Airport', 'Jalālābād', 93, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Auckland International Airport', 'Hotonj', 93, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gag Island Airport', 'Ulan Hua', 62, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Marshall Don Hunter Sr Airport', 'Bang Racham', 71, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Wiarton Airport', 'Yanhe', 64, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Satu Mare Airport', 'Benito Juarez', 56, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tampa North Aero Park Airport', 'Vratsa', 96, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sioux Gateway Col. Bud Day Field', 'Nong Kung Si', 67, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ararat Airport', 'Yong’an', 100, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mayo Airport', 'Dūrā al Qar‘', 42, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ngoma Airport', 'Jilib', 20, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Böblingen Flugfeld', 'Bagu', 26, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Vinh Airport', 'Tianyuan', 75, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pattaya Airpark', 'Tiblawan', 25, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lambarene Airport', 'Debesy', 86, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Millville Municipal Airport', 'Qızılhacılı', 48, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Connemara Regional Airport', 'Danchang', 30, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dillingham Airport', 'Mongo', 91, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fukuoka Airport', 'Gabao', 2, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Wittman Regional Airport', 'Si Sa Ket', 77, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kempegowda International Airport', 'Avignon', 41, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Thangool Airport', 'Sogod', 13, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Berlevåg Airport', 'Jinhaihu', 58, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Chigorodó Airport', 'Suay', 59, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jiamusi Airport', 'Stockholm', 88, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Charata Airport', 'Stenungsund', 7, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Eugene F. Correira International Airport', 'Ushumun', 6, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kruger Mpumalanga International Airport', 'Inyati', 73, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Man Airport', 'Jiangning', 41, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ahuas Airport', 'Calaba', 55, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Golfo de Morrosquillo Airport', 'Tongzi', 24, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Golfito Airport', 'Lanzhong', 83, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('San Fernando Airport', 'Khanu Woralaksaburi', 64, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bulagtai Resort Airport', 'Gaoshan', 12, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Washington Island Airstrip', 'Wudong', 87, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Grand Coulee Dam Airport', 'Cigarogol', 98, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Esperadinha Airport', 'Qanliko’l', 99, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yonaguni Airport', 'Dhamār', 46, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Derim Airport', 'Al Jumūm', 74, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Petit Jean Park Airport', 'Nizhniy Lomov', 16, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Muir Army Air Field (Fort Indiantown Gap) Airport', 'Costa de Rios Frios', 58, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Manari Airport', 'Mamu', 38, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tep Tep Airport', 'Pocrí', 76, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Westfield-Barnes Regional Airport', 'Djibouti', 78, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Binaka Airport', 'Era', 73, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Châteauroux-Déols "Marcel Dassault" Airport', 'Qingliu', 64, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nemiscau Airport', 'Stará Paka', 24, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mopah Airport', 'Lianglin', 66, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cabo Frio Airport', 'Novogornyy', 55, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rotorua Regional Airport', 'Tebingtinggi', 29, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Laguna Army Airfield', 'Vellinge', 10, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Brussels Airport', 'Kurba', 96, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sakon Nakhon Airport', 'Orléans', 87, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Northeast Iowa Regional Airport', 'Schifflange', 19, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Leipzig/Halle Airport', 'Darmasari', 5, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Las Brujas Airport', 'Leuwipicung', 40, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Changzhi Airport', 'Lahad Datu', 56, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cedar City Regional Airport', 'Gardawice', 57, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Abeid Amani Karume International Airport', 'Qixian', 43, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dong Hoi Airport', 'Darovskoy', 55, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ust-Maya Airport', 'Sabi', 84, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Savannakhet Airport', 'Guanchao', 96, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Greater Rochester International Airport', 'Itinga', 41, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pirapora Airport', 'Walferdange', 45, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Abbeville', 'Tembang', 99, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lindu Airport', 'Dingtou', 86, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jeh Airport', 'Karagandy', 64, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lawrence Municipal Airport', 'Chroustovice', 44, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sogndal Airport', 'Dubrovka', 48, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Keesler Air Force Base', 'Všenory', 12, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gayndah Airport', 'Zhetian', 82, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jaisalmer Airport', 'Jinshan', 28, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Garden City Regional Airport', 'Levashi', 57, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mariposa Yosemite Airport', 'Kawasaki', 53, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Vancouver International Airport', 'Xinhe', 53, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Keflavik International Airport', 'Kil', 20, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fangatau Airport', 'Bromma', 96, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Vicecomodoro Angel D. La Paz Aragonés Airport', 'Xianglong', 32, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pleiku Airport', 'Sanqishi', 60, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Chiquimula Airport', 'Dioknisi', 49, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fredericton Airport', 'Yanaoca', 88, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hluhluwe Airport', 'Caromatan', 97, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tainan Airport', 'Arthur’s Town', 59, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yonaguni Airport', 'Asan', 11, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tupile Airport', 'Deskáti', 91, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tuscaloosa Regional Airport', 'Rancakole', 14, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Francisco B. Reyes Airport', 'Manlucahoc', 12, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lumberton Regional Airport', 'Podporozh’ye', 84, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Malé International Airport', 'Tunjuk Selatan', 94, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ivishak Airport', 'Aguilares', 82, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Esperance Airport', 'Shaghat', 71, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dijon-Bourgogne Airport', 'Santa Cruz', 95, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Thomasville Regional Airport', 'Muting', 76, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ambohibary Airport', 'Zárkos', 70, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sayaboury Airport', 'Río de Oro', 92, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Abraham Lincoln Capital Airport', 'Xylókastro', 84, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Torembi Airport', 'Plateliai', 87, 13);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Albuquerque International Sunport', 'Yidian', 22, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Algeciras Heliport', 'Ar Rudayyif', 27, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Armando Schwarck Airport', 'Jaboatão', 61, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kangding Airport', 'Colquemarca', 33, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Johnson County Airport', 'Puerto Parra', 35, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Donaldson Field Airport', 'Xiaoyue', 59, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Helenvale Airport', 'Alofi', 89, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Butterworth Airport', 'Ouro Preto', 100, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ketchikan Harbor Seaplane Base', 'Chigorodó', 67, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Enontekio Airport', 'Bururi', 100, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Moffett Federal Airfield', 'Selaawi', 99, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Vicksburg Municipal Airport', 'Luhansk', 51, 13);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gothenburg City Airport', 'Kristianstad', 65, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mojica Airport', 'Orléans', 76, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Letfotar Airport', 'Nysa', 64, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Metz-Frescaty (BA 128) Air Base', 'Pavlovsk', 20, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('California Redwood Coast-Humboldt County Airport', 'Nguékhokh', 10, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Salima Airport', 'Tabon', 83, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Prefeito Doutor João Silva Filho Airport', 'Verrettes', 66, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Brussels Airport', 'Trenggulunan', 49, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Uvol Airport', 'Póvoa', 65, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Inisheer Aerodrome', 'Flic en Flac', 58, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Biaugunu Airport', 'Priargunsk', 68, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Las Brujas Airport', 'Caibiran', 67, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Aomori Airport', 'Shuangxi', 40, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Faaite Airport', 'Shreveport', 99, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ngukurr Airport', 'Arrifes', 81, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ghat Airport', 'Bla', 89, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Wausau Downtown Airport', 'Shekou', 64, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tindouf Airport', 'Dongping', 54, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Santana do Araguaia Airport', 'Pameungpeuk', 62, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Monbetsu Airport', 'Sibayo', 72, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mekambo Airport', 'Magetlegar', 60, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Brookings Airport', 'Bertioga', 33, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Harry Stern Airport', 'Carrefour', 63, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Presidente João Suassuna Airport', 'Boé', 100, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Riyadh Air Base', 'Jinghai', 90, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kanpur Airport', 'Akkol’', 6, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Louisville Winston County Airport', 'Pedra Branca', 13, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rivière-du-Loup Airport', 'Nanfeng', 90, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('La Désirade Airport', 'Bagong Barrio', 15, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rosecrans Memorial Airport', 'Bao’an', 76, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('La Roche-sur-Yon Airport', 'Socorro', 42, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Anderson Municipal Darlington Field', 'Waiholo', 87, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Catalão Airport', 'Noramarg', 80, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('El Kharga Airport', 'Wassa-Akropong', 89, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Manzhouli Xijiao Airport', 'Gråbo', 31, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Moyale Airport', 'Ambato Boeny', 1, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Coimbatore International Airport', 'Bazar-Korgon', 94, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('San José De Chiquitos Airport', 'Kurgan', 6, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Senador Nilo Coelho Airport', 'Pavlovskaya', 40, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ust-Kamennogorsk Airport', 'Měcholupy', 36, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mainoru Airstrip', 'Konārak', 90, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Guymon Municipal Airport', 'Nuamuzi', 67, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('RAF Northolt', 'Lisičani', 57, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pindiu Airport', 'Basco', 34, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gonder Airport', 'Mengxingzhuang', 78, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Carora Airport', 'Souran', 8, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bisbee Municipal Airport', 'Dalsjöfors', 24, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Redstone Army Air Field', 'Puerto Princesa', 3, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Langeoog Airport', 'Bilozerka', 16, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lightning Ridge Airport', 'Sơn Hà', 1, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zigong Airport', 'Rusnė', 77, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bamiyan Airport', 'Changuinola', 9, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zanaga Airport', 'Zhendong', 94, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Southern Cross Airport', 'Dasiping', 75, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('El Borma Airport', 'Xidoupu', 89, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Shahid Ashrafi Esfahani Airport', 'As Sulayyil', 80, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tom Price Airport', 'Gotse Delchev', 11, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bhurban Heliport', 'Barakī Barak', 13, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hampton Municipal Airport', 'Ubajami', 90, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Santana do Araguaia Airport', 'Wachira Barami', 51, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tekin Airport', 'Kembé', 27, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Payson Airport', 'Smoky Lake', 14, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Olive Branch Airport', 'Murów', 12, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rodríguez Ballón International Airport', 'Gal’bshtadt', 18, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Harrisburg International Airport', 'Chenzhouzhai', 28, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Biarritz-Anglet-Bayonne Airport', 'Knysna', 45, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Augusta Regional At Bush Field', 'Utabi', 9, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Wright AAF (Fort Stewart)/Midcoast Regional Airport', 'Timaru', 33, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Musina(Messina) Airport', 'Kwidzyn', 78, 13);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Monte Santo de Minas Airport', 'Tabaquite', 80, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Handan Airport', 'Estacion', 2, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pamplona Airport', 'Sainte-Agathe-des-Monts', 39, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rock Hill - York County Airport', 'Kalangan', 72, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Metropolitan Airport', 'Nice', 90, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Siglufjörður Airport', 'Międzybrodzie Bialskie', 3, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Akulivik Airport', 'Sutukoba', 25, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tanjung Harapan Airport', 'Ōmamachō-ōmama', 8, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Teniente Vidal Airport', 'Sintung Timur', 23, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Miyazaki Airport', 'Cachoeiro de Itapemirim', 36, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kincardine Municipal Airport', 'Maliana', 93, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('York Landing Airport', 'Gaoqiao', 98, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kingaroy Airport', 'Alegrete', 79, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Amata Airport', 'Penha Longa', 15, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jwaneng Airport', 'Tonshayevo', 93, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Spichenkovo Airport', 'Pujijie', 26, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mário Pereira Lopes–São Carlos Airport', 'Pico da Pedra', 19, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Richards-Gebaur Air Force Base', 'Ħamrun', 60, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Merced Regional Macready Field', 'Yangyuan', 43, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Qeshm International Airport', 'Erdaocha', 96, 47);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ndjili International Airport', 'Danirai', 4, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Manchester Airport', 'Lianghe', 96, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Reims-Champagne (BA 112) Air Base', 'Guanli', 14, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Asirim Airport', 'Waiholo', 41, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cincinnati Municipal Airport Lunken Field', 'Jastrebarsko', 15, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('La Désirade Airport', 'Campo de la Cruz', 8, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Langley Air Force Base', 'Rio Claro', 83, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Siuna', 'Wonokromo', 64, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hammerfest Airport', 'Sikonge', 47, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Inta Airport', 'Guatire', 61, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Qala-I-Naw Airport', 'Pineleng', 53, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Almirante Padilla Airport', 'Thị Trấn Văn Quan', 61, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('DLF Airport', 'Aasiaat', 39, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Presidente Juscelino Kubistschek International Airport', 'Miskolc', 19, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ahwaz Airport', 'Gelgaudiškis', 66, 7);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Carauari Airport', 'Xiangfeng', 19, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Essen Mulheim Airport', 'Nackawic', 71, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Seronera Airport', 'Akhaldaba', 85, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Juan H White Airport', 'Konibodom', 94, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Robin Hood Doncaster Sheffield Airport', 'Imrīsh', 18, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('North Spirit Lake Airport', 'Yaizu', 37, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bajura Airport', 'Kokemäki', 63, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Francisco de Assis Airport', 'Jobabo', 76, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Quepos Managua Airport', 'Fangtai', 74, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Phnom Penh International Airport', 'Bīr Nabālā', 96, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Northeastern Regional Airport', 'Kalinkavichy', 92, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Carauari Airport', 'Beizhang', 96, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Salerno Costa d''Amalfi Airport', 'Aveiro', 17, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Shakiso Airport', 'Ngawi', 99, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tol Airport', 'Särö', 66, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pathankot Airport', 'Trelew', 74, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nullagine Airport', 'Kuangyuan', 82, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Petawawa Airport', 'Yeşilköy', 82, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Port Simpson Seaplane Base', 'Sulangan', 18, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Abaco I Walker C Airport', 'Zhengchang', 85, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Portoroz Airport', 'Dahe', 17, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yichang Sanxia Airport', 'Laojunmiao', 51, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Suki Airport', 'Kwikila', 6, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Arar Domestic Airport', 'Shingū', 24, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tambao Airport', 'Tostado', 26, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Little Rock Air Force Base', 'Pukhavichy', 9, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Andrau Airpark', 'Puning', 40, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jinja Airport', 'Banff', 19, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lensk Airport', 'Maoyang', 16, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Amchitka Army Airfield', 'Swords', 59, 32);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cherrabun Airport', 'Safara', 97, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Basrah International Airport', 'Urho', 98, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Marion County Regional Airport', 'Rongcheng', 67, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nanchong Airport', 'Veshnyaki', 26, 45);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('San Fernando Airport', 'Parakou', 73, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hachijojima Airport', 'Trzcinica', 96, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Schefferville Airport', 'Nueva Cajamarca', 96, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kebar Airport', 'Riang Tengah', 22, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kalgoorlie Boulder Airport', 'Macau', 62, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yuma MCAS/Yuma International Airport', 'Dvinskoy', 11, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Phan Thiet Airport', 'Cemplang', 97, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Nouméa Magenta Airport', 'Padre Bernardo', 52, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Creston Municipal Airport', 'Lamam', 45, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pureni Airport', 'Kalāt', 37, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bowers Field', 'Kishk-e Nakhūd', 39, 6);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Deer Park Airport', 'Thị Trấn Na Hang', 7, 1);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Phan Rang Airport', 'Zelenoborskiy', 76, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lime Acres Finsch Mine Airport', 'Koilás', 41, 43);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Timaru Airport', 'Pidvolochys’k', 56, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kenora Airport', 'Kiên Lương', 24, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Karumba Airport', 'Sarnia', 66, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ely Airport Yelland Field', 'Gaxung', 32, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Buckley Air Force Base', 'Shanmuqiao', 27, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Inverell Airport', 'Ранковце', 96, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mayne Island Seaplane Base', 'Rathwire', 79, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Dimokritos Airport', 'Monte', 31, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cadjehoun Airport', 'Boyany', 29, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Port Pirie Airport', 'Langtad', 71, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Powell Municipal Airport', 'Petřvald', 44, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pimenta Bueno Airport', 'Nazca', 6, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gao Airport', 'San Miguel', 11, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lamidanda Airport', 'Polanka Wielka', 12, 36);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Yerington Municipal Airport', 'Banovo Polje', 45, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lobatse Airport', 'Nova Era', 54, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Pitalito Airport', 'Wangong', 73, 30);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fort Stockton Pecos County Airport', 'Vila Franca', 97, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mungeranie Airport', 'København', 99, 35);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cairns International Airport', 'Yashio-shi', 88, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ahuas Airport', 'Jelisavac', 20, 22);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bajura Airport', 'Cigebrok', 65, 8);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Guaratinguetá Airport', 'Melgar', 82, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Oki Airport', 'Socorro', 95, 2);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jeju International Airport', 'Göteborg', 76, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Brunette Downs Airport', 'Linköping', 24, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cuamba Airport', 'Zbąszynek', 78, 21);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Fort Resolution Airport', 'Laramate', 27, 3);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kulusuk Airport', 'Suncun', 20, 4);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('King Island Airport', 'Tajrīsh', 47, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Salem Municipal Airport/McNary Field', 'Dąbrowice', 87, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sherbrooke Airport', 'Chornukhyne', 35, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gnarowein Airport', 'Karangboyo', 22, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Leonard M Thompson International Airport', 'Hoeryŏng', 89, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Faisalabad International Airport', 'Deventer', 42, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tchibanga Airport', 'Karobokan', 82, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Landivisiau Air Base', 'Leleque', 54, 13);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bialla Airport', 'Cirangrang', 32, 25);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lashio Airport', 'Hrvatska Kostajnica', 34, 23);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Karanambo Airport', 'Shreveport', 60, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Arvaikheer Airport', 'Waitara', 83, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Sultan Thaha Airport', 'Palca', 70, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ingjaldssanður Airport', 'Kotadukuh', 42, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zemio Airport', 'Ovalle', 19, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Parachinar Airport', 'San José de Mayo', 58, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Renner Field-Goodland Municipal Airport', 'Sirib', 67, 18);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Bern Belp Airport', 'Labège', 10, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kokoda Airport', 'Orlando', 52, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Inca Manco Capac International Airport', 'Pražmo', 1, 39);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Macagua Airport', 'Leshan', 6, 48);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Hugo Cantergiani Regional Airport', 'Anxiang', 48, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Edmonton International Airport', 'Donggaocun', 75, 28);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('RAF Mildenhall', 'Panayagan', 8, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Moosonee Airport', 'Karangkancana', 72, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Charlotte County Airport', 'Yuanguping', 2, 20);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('El Tuqui Airport', 'Moro', 16, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Morristown Municipal Airport', 'Kotli Lohārān', 23, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Maryborough Airport', 'Cileunyi', 74, 10);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Minneapolis-St Paul International/Wold-Chamberlain Airport', 'Nedryhayliv', 89, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Faaite Airport', 'Horad Pinsk', 2, 49);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Stockton Metropolitan Airport', 'Venëv', 92, 26);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gordon Downs Airport', 'Morani', 45, 15);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Senggo Airport', 'Laguna Salada', 1, 40);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tobolsk Airport', 'Santa Adélia', 23, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Resistencia International Airport', 'Huayan', 20, 48);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Linköping City Airport', 'Seremban', 97, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Kol Airport', 'Xinmin', 28, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Oakey Airport', 'Sovetskiy', 26, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Røst Airport', 'Rio Claro', 16, 38);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Icy Bay Airport', 'Žďár nad Sázavou Druhy', 95, 50);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Soewondo Air Force Base', 'Draginje', 52, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Portland Troutdale Airport', 'Krasnogorsk', 90, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Les Bases Airport', 'Andop', 67, 33);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Tavie Airport', 'Cavaillon', 33, 37);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Diosdado Macapagal International Airport', 'Anna Regina', 16, 19);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cushing Municipal Airport', 'Cizhu', 45, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Trincomalee Harbor Waterdrome', 'Rasskazovo', 88, 14);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Rabil Airport', 'Prévost', 15, 31);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('RAF Coningsby', 'Hongyuan', 85, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Gatlinburg-Pigeon Forge Airport', 'Liancheng', 72, 41);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Eilat Airport', 'Kobyzhcha', 20, 42);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ijuí Airport', 'Sacramento', 73, 24);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Shah Mokhdum Airport', 'Tabia', 25, 34);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Creil Air Base', 'Saposoa', 54, 9);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Anyang Airport', 'Müllendorf', 82, 5);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Zabrat Airport', 'Cortinhas', 24, 12);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Lac Brochet Airport', 'Wako', 88, 44);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Mangochi Airport', 'Onguday', 90, 11);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Cortina Airport', 'Osiek', 59, 17);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Iginniarfik', 'Heredia', 50, 27);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Ernabella Airport', 'Togu', 73, 29);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Shanghai Hongqiao International Airport', 'Nepalgunj', 80, 16);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Jim Hamilton L.B. Owens Airport', 'Azun Atme', 100, 46);
insert into Airports (name, city, runwaycapacity, storecapacity) values ('Wawa Airport', 'Apeldoorn', 34, 19);


SELECT * FROM Airports